spring.application.name=music-discovery-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/music_discovery
spring.datasource.username=music_app_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false