CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20)  NOT NULL,
    email VARCHAR(75)  NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE artists (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     artist_name VARCHAR(200) NOT NULL
);


CREATE TABLE songs (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     title VARCHAR(200) NOT NULL ,
     duration_seconds INTEGER CHECK(duration_seconds > 0) NOT NULL ,
     artist_id BIGINT NOT NULL,
     FOREIGN KEY (artist_id) REFERENCES artists (id)
);

CREATE TABLE playlists (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(200) NOT NULL,
     user_id BIGINT NOT NULL ,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE  CASCADE
);


CREATE TABLE playlist_songs (
     playlist_id BIGINT NOT NULL,
     song_id BIGINT NOT NULL,
     position INTEGER NOT NULL CHECK( position > 0 ),
     added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY (playlist_id,song_id),
     FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
     FOREIGN KEY (song_id) REFERENCES  songs(id) ON DELETE  CASCADE
);

CREATE TABLE ratings (
     user_id BIGINT NOT NULL,
     song_id BIGINT NOT NULL,
     rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
     PRIMARY KEY (user_id, song_id),
     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
     FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
);